[package]
name = "aptos-gas"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Gas metering for the Aptos blockchain"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
move-binary-format = { git = "https://github.com/aptos-labs/move-private", rev = "d75b4e9a97fdc4d4dc16669ea657134d692034c5" }
move-core-types = { git = "https://github.com/aptos-labs/move-private", rev = "d75b4e9a97fdc4d4dc16669ea657134d692034c5" }
move-stdlib = { git = "https://github.com/aptos-labs/move-private", rev = "d75b4e9a97fdc4d4dc16669ea657134d692034c5" }
move-table-extension = { git = "https://github.com/aptos-labs/move-private", rev = "d75b4e9a97fdc4d4dc16669ea657134d692034c5" }
move-vm-types = { git = "https://github.com/aptos-labs/move-private", rev = "d75b4e9a97fdc4d4dc16669ea657134d692034c5" }

aptos-types = { path = "../../types" }
framework = { path = "../framework" }
gas-algebra-ext = { path = "../gas-algebra-ext" }

[features]
testing = ["move-stdlib/testing"]
