{
 "title": "Mempool",
 "time": { "from": "2022-09-16T18:16:31.000Z", "to": "2022-09-16T18:32:16.000Z" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "chain_name", "query": { "query": "label_values(chain_name)" } },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(kubernetes_pod_name)"
    }
   },
   { "name": "role", "query": { "query": "label_values(role)" } },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mempool size",
   "type": "timeseries",
   "description": "total number of transactions in mempool",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aptos_core_mempool_index_size{chain_name=~\"$chain_name\", namespace=~\"$namespace\", index=\"system_ttl\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Successful Txn Insertion Rate",
   "type": "timeseries",
   "description": "rate of mempool insertion of txn",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role, status) (rate(aptos_shared_mempool_transactions_processed{chain_name=~\"$chain_name\", namespace=~\"$namespace\", status=\"success\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]))",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} - {{status}}"
    }
   ]
  },
  {
   "title": "Active Upstream Peers",
   "type": "timeseries",
   "description": "number of live peers a node can broadcast to in each network",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role, network) (aptos_mempool_active_upstream_peers_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}  ({{network}} network)"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "New transactions received rate",
   "type": "timeseries",
   "description": "rate of new transactions received from other peers or JSON-RPC",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role, network, sender) (rate(aptos_shared_mempool_transactions_processed{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]))",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} <- ({{network}} network, {{sender}})"
    }
   ]
  },
  {
   "title": "Txn Removal Rate",
   "type": "timeseries",
   "description": "Rate at which txns are removed (via commit) from mempool",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_core_mempool_removed_txns_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Avg E2E Txn Commit Latency",
   "type": "timeseries",
   "description": "The time between Mempool receiving the transaction and time to be committed.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "aptos_core_mempool_txn_commit_latency_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", stage=\"commit_accepted\"} / aptos_core_mempool_txn_commit_latency_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", stage=\"commit_accepted\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Duplicate (Idempotent) Txn Rate",
   "type": "timeseries",
   "description": "Rate at which duplicate (idempotent) txns are received at mempool",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_core_mempool_idempotent_txns_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Client-expired txns",
   "type": "timeseries",
   "description": "rate of number of transactions that expired in mempool based on client-specified expiration time",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_core_mempool_gc_latency_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"client_expiration\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} : {{status}}"
    }
   ]
  },
  {
   "title": "System-expired Txns",
   "type": "timeseries",
   "description": "Rate of number of transactions that expired in mempool based on mempool-specified expiration time",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_core_mempool_gc_latency_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"system_ttl\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} : {{status}}"
    }
   ]
  },
  {
   "title": "Successful transaction validation rate",
   "type": "timeseries",
   "description": "rate of transactions that were successfully validated before mempool insertion\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role, network, sender) (rate(aptos_shared_mempool_transactions_processed{chain_name=~\"$chain_name\", namespace=~\"$namespace\", status!=\"vm_validation\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]))",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} <- ({{network}} network:{{sender}})"
    }
   ]
  },
  {
   "title": "VM Failed Txns Rate",
   "type": "timeseries",
   "description": "rate of submitted txns that failed to pass the VM validation",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role, network, sender) (rate(aptos_shared_mempool_transactions_processed{chain_name=~\"$chain_name\", namespace=~\"$namespace\", status=\"vm_validation\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]))",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} <- ({{network}} network:{{sender}})"
    }
   ]
  },
  {
   "title": "Failed Mempool Insertion Rate",
   "type": "timeseries",
   "description": "rate of transactions that passed VM validation but were rejected from mempool",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_shared_mempool_transactions_processed{chain_name=~\"$chain_name\", namespace=~\"$namespace\", status!=\"success\", status!=\"vm_validation\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} <- ({{network}} network:{{sender}}) -  {{status}}"
    }
   ]
  },
  { "title": "Indexes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Timeline Index",
   "type": "timeseries",
   "description": "number of transactions ready for broadcast in core mempool ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aptos_core_mempool_index_size{chain_name=~\"$chain_name\", namespace=~\"$namespace\", index=\"timeline\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Priority Index",
   "type": "timeseries",
   "description": "transactions ready for consensus",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aptos_core_mempool_index_size{chain_name=~\"$chain_name\", namespace=~\"$namespace\", index=\"priority\", role=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Parking Lot Index",
   "type": "timeseries",
   "description": "number of transactions in parking lot index. These transactions are not ready for broadcast or consensus",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aptos_core_mempool_index_size{chain_name=~\"$chain_name\", namespace=~\"$namespace\", index=\"parking_lot\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Mempool size (bytes)",
   "type": "timeseries",
   "description": "total size in bytes of transactions in mempool",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aptos_core_mempool_index_size{chain_name=~\"$chain_name\", namespace=~\"$namespace\", index=\"size_bytes\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  { "title": "Outgoing Txn Broadcasts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Average Broadcast Size",
   "type": "timeseries",
   "description": "average number of transactions in a single broadcast",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_shared_mempool_transaction_broadcast_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(aptos_shared_mempool_transaction_broadcast_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} -> ({{network}})"
    }
   ]
  },
  {
   "title": "Broadcasted Txns Rate",
   "type": "timeseries",
   "description": "rate of transactions broadcasted to other peers",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_shared_mempool_transaction_broadcast_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} -> ({{network}})"
    }
   ]
  },
  {
   "title": "Broadcast Rate",
   "type": "timeseries",
   "description": "avg number of broadcasts / sec",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_broadcast_latency_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} -> ({{network}})"
    }
   ]
  },
  {
   "title": "Average Broadcast Execution Latency",
   "type": "timeseries",
   "description": "avg time it takes to execute a broadcast",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_broadcast_latency_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(aptos_mempool_broadcast_latency_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} -> ({{network}})"
    }
   ]
  },
  {
   "title": "Average Broadcast Roundtrip Time",
   "type": "timeseries",
   "description": "average time b/w broadcast sent and ACK coming back for it",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_shared_mempool_broadcast_roundtrip_latency_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(aptos_shared_mempool_broadcast_roundtrip_latency_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} -> ({{network}})"
    }
   ]
  },
  {
   "title": "Pending Broadcasts",
   "type": "timeseries",
   "description": "number of sent broadcasts awaiting an ACK",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role, network) (aptos_shared_mempool_pending_broadcasts_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} -> ({{network}})"
    }
   ]
  },
  {
   "title": "Expired Rebroadcast Rate",
   "type": "timeseries",
   "description": "rate of broadcasts that are retrying expired braodcasts (that did not get back an ACK in window of time)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_shared_mempool_rebroadcast_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"expired\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} -> {{network}}"
    }
   ]
  },
  {
   "title": "Retry Rebroadcast",
   "type": "timeseries",
   "description": "rate of broadcasts that are retrying past broadcasts that received a retry ACK",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_shared_mempool_rebroadcast_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"retry\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} -> ({{network}})"
    }
   ]
  },
  {
   "title": "Backpressure Broadcast",
   "type": "timeseries",
   "description": "rate of broadcasts that were executed as a backpressure broadcast",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_shared_mempool_rebroadcast_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"backpressure\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} -> {{network}}"
    }
   ]
  },
  { "title": "Commit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Accepted Transaction Commit Rate",
   "type": "timeseries",
   "description": "Rate of accepted transactions committed per second (notified from state sync)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_service_transactions_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"commit_accepted\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])\n",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Rejected Transaction Commit Rate",
   "type": "timeseries",
   "description": "rate of rejected committed transactions (notified from consensus)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_service_transactions_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"commit_rejected\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])\n",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Block size",
   "type": "timeseries",
   "description": "Average size of consensus blocks pulled from mempool",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_service_transactions_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"get_block\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval]) / rate(aptos_mempool_service_transactions_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"get_block\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Avg latency handle commit (accepted)",
   "type": "timeseries",
   "description": "average time it takes for mempool to process a commit of accepted transactions (sent from state sync)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_service_latency_ms_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"commit_accepted\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(aptos_mempool_service_latency_ms_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"commit_accepted\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Avg latency handle commit (rejected)",
   "type": "timeseries",
   "description": "avg time it takes to process committed rejected txns",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_service_latency_ms_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"commit_rejected\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval])/rate(aptos_mempool_service_latency_ms_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"commit_rejected\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Avg latency for get_block",
   "type": "timeseries",
   "description": "Avg time it takes for consensus to pull block from mempool",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_service_latency_ms_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"get_block\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval]) / rate(aptos_mempool_service_latency_ms_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"get_block\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Event Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Incoming events rate",
   "type": "timeseries",
   "description": "rate of shared mempool events from peers",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_shared_mempool_events{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} - {{event}}"
    }
   ]
  },
  {
   "title": "Shared Mempool Task Start Latency",
   "type": "timeseries",
   "description": "average time it takes for mempool to start an async task",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_bounded_executor_spawn_latency_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", stage=\"start\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(aptos_mempool_bounded_executor_spawn_latency_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", stage=\"start\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} - {{task}}"
    }
   ]
  },
  {
   "title": "Average Txn Processing Latency",
   "type": "timeseries",
   "description": "avg time it takes to process incoming transactions, per incoming submission",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_shared_mempool_request_latency_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(aptos_shared_mempool_request_latency_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} <- ({{network}} network:{{sender}})"
    }
   ]
  },
  {
   "title": "Average VM Validation Latency",
   "type": "timeseries",
   "description": "avg time it takes to VM-validate txns in a submission",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_process_txn_breakdown_latency_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", portion=\"vm_validation\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(aptos_mempool_process_txn_breakdown_latency_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", portion=\"vm_validation\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Average DB Read Latency",
   "type": "timeseries",
   "description": "latency of db read when validating transaction",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_process_txn_breakdown_latency_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", portion=\"storage_fetch\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(aptos_mempool_process_txn_breakdown_latency_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", portion=\"storage_fetch\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Main loop latency",
   "type": "timeseries",
   "description": "Duration of each run of the event loop",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_main_loop_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(aptos_mempool_main_loop_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Mempool Service Timeout",
   "type": "timeseries",
   "description": "number of timeouts on a mempool service request (from consensus/state sync)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_service_latency_ms_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", result=\"fail\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} - {{type}}"
    }
   ]
  },
  {
   "title": "DB error",
   "type": "timeseries",
   "description": "number of times a DB error occurred",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_db_error_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "JSON RPC Callback Timeout",
   "type": "timeseries",
   "description": "number of timeouts in callback to JSON RPC",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_json_rpc_callback_fail_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Network Send Fail",
   "type": "timeseries",
   "description": "number of times a aptos network send failed",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_network_send_fail_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "VM Reconfiguration Failure",
   "type": "timeseries",
   "description": "number of times reconfiguration of VM failed",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_vm_reconfig_update_fail_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Core Mempool Invariant Violation",
   "type": "timeseries",
   "description": "number of times core mempool invariant was violated",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_core_mempool_invariant_violated_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=\"$kubernetes_pod_name\", role=\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Unexpected Network Messages",
   "type": "timeseries",
   "description": "rate of unexpected network messages received",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_unexpected_network_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} <- {{network}}:{{peer}}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 } },
  {
   "title": "Garbage Collection Event Rate",
   "type": "timeseries",
   "description": "Number of times garbage-collection event occurred (regardless of how many txns were actually removed in the event)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_core_mempool_gc_event_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"system_ttl\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "GC Latency",
   "type": "timeseries",
   "description": "how long a transaction stayed in mempool before being garbage-collected",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_core_mempool_gc_latency_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])/rate(aptos_core_mempool_gc_latency_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  { "title": "Network Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 } },
  {
   "title": "Dropped Messages",
   "type": "timeseries",
   "description": "number of messages dropped from mempool channel sender",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aptos_mempool_pending_network_events{chain_name=~\"$chain_name\", namespace=~\"$namespace\", state=\"dropped\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Messages Enqueued Rate",
   "type": "timeseries",
   "description": "rate of messages being enqueued to be sent out",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_pending_network_events{chain_name=~\"$chain_name\", namespace=~\"$namespace\", state=\"enqueued\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Messages Dequeued Rate",
   "type": "timeseries",
   "description": "Rate of messages dequeued from mempool network sender",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_pending_network_events{chain_name=~\"$chain_name\", namespace=~\"$namespace\", state=\"dequeued\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Messages Queued",
   "type": "timeseries",
   "description": "Messages currently queued to be sent out",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role) (aptos_mempool_pending_network_events{chain_name=~\"$chain_name\", namespace=~\"$namespace\", state=\"enqueued\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}) - sum by (kubernetes_pod_name, role)  (aptos_mempool_pending_network_events{chain_name=~\"$chain_name\", namespace=~\"$namespace\", state=\"dequeued\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Sent ACKs (backoff/retry)",
   "type": "timeseries",
   "description": "rate of backoff/retry ACKs sent",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aptos_shared_mempool_ack_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", direction=\"sent\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} -> {{network}} - {{type}}"
    }
   ]
  },
  {
   "title": "ACKs Received",
   "type": "timeseries",
   "description": "rate of retry/backpressure ACKs received",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_shared_mempool_ack_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", direction=\"received\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} <- {{network}} - {{type}}"
    }
   ]
  }
 ]
}